Construct Conv1d with input_shape=None argument
This fixes an issue where transforming a Conv1D node results in error
message TypeError: Conv1d.__init__() missing 1 required positional
argument: 'input_shape'.